# Generated by Django 5.2.9 on 2026-06-24 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=64)),
                ('result', models.JSONField()),
                ('ttl_days', models.PositiveIntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_caches', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Harita Cache',
                'verbose_name_plural': "Harita Cache'leri",
                'indexes': [models.Index(fields=['tenant', 'cache_key'], name='maps_mapcac_tenant__e61997_idx')],
                'unique_together': {('tenant', 'cache_key')},
            },
        ),
        migrations.CreateModel(
            name='MapQuotaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', "Global (tüm tenant'lar)"), ('tenant', 'Tenant özel')], db_index=True, default='tenant', max_length=16)),
                ('api_type', models.CharField(choices=[('geocode', 'Geocoding'), ('directions', 'Directions'), ('places', 'Places (autocomplete)'), ('distance_matrix', 'Distance Matrix'), ('static_map', 'Static Map'), ('js', 'Maps JavaScript')], db_index=True, max_length=32)),
                ('monthly_limit', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Global politika icin bos birakin.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_quota_policies', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_map_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Harita Kota Politikası',
                'verbose_name_plural': 'Harita Kota Politikaları',
                'indexes': [models.Index(fields=['scope', 'api_type', 'is_active'], name='maps_mapquo_scope_8a2a45_idx'), models.Index(fields=['tenant', 'api_type', 'is_active'], name='maps_mapquo_tenant__faf17f_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'tenant', 'api_type'), name='uniq_quota_policy_scope_tenant_api')],
            },
        ),
        migrations.CreateModel(
            name='TenantMapQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.CharField(choices=[('geocode', 'Geocoding'), ('directions', 'Directions'), ('places', 'Places (autocomplete)'), ('distance_matrix', 'Distance Matrix'), ('static_map', 'Static Map'), ('js', 'Maps JavaScript')], db_index=True, max_length=32)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('last_request_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_quotas', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Harita Kotası',
                'verbose_name_plural': 'Tenant Harita Kotaları',
                'indexes': [models.Index(fields=['tenant', 'api_type', 'year', 'month'], name='maps_tenant_tenant__c85d28_idx'), models.Index(fields=['tenant', 'year', 'month'], name='maps_tenant_tenant__6182ba_idx')],
                'unique_together': {('tenant', 'api_type', 'year', 'month')},
            },
        ),
    ]
