# Generated by Django 5.1.15 on 2026-09-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapcache',
            options={'verbose_name': 'Harita Önbelleği', 'verbose_name_plural': 'Harita Önbellekleri'},
        ),
    ]
