# Generated by Django 5.2.9 on 2026-06-18 06:50

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hire_date', models.DateField(default=datetime.date.today, verbose_name='İşe Alım Tarihi')),
                ('is_online', models.BooleanField(default=False, verbose_name='Çevrimiçi')),
                ('last_online', models.DateTimeField(blank=True, null=True, verbose_name='Son Görülme')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL, verbose_name='Teknik Personel')),
            ],
            options={
                'verbose_name': 'Teknisyen Profili',
                'verbose_name_plural': 'Teknisyen Profilleri',
            },
        ),
        migrations.CreateModel(
            name='TechnicianLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Konum')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Enlem')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Boylam')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_locations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_locations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Teknisyen Konumu',
                'verbose_name_plural': 'Teknisyen Konumları',
            },
        ),
        migrations.CreateModel(
            name='TechnicianPermissions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_manage_customers', models.BooleanField(default=False, verbose_name='Müşterileri Yönetebilir')),
                ('can_manage_inventory', models.BooleanField(default=False, verbose_name='Envanteri Yönetebilir')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Kullanıcıları Yönetebilir')),
                ('can_manage_accounting', models.BooleanField(default=False, verbose_name='Muhasebeyi Yönetebilir')),
                ('can_manage_notifications', models.BooleanField(default=False, verbose_name='Bildirimleri Yönetebilir')),
                ('can_manage_hr', models.BooleanField(default=False, verbose_name='İnsan Kaynaklarını Yönetebilir')),
                ('can_manage_reports', models.BooleanField(default=False, verbose_name='Raporları Yönetebilir')),
                ('can_manage_settings', models.BooleanField(default=False, verbose_name='Ayarları Yönetebilir')),
                ('can_manage_services', models.BooleanField(default=False, verbose_name='Servisleri Yönetebilir')),
                ('can_manage_technicians', models.BooleanField(default=False, verbose_name='Teknisyenleri Yönetebilir')),
                ('can_use_global_search', models.BooleanField(default=False, verbose_name='Global Aramayı Kullanabilir')),
                ('technician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='technicians.technician', verbose_name='Teknisyen')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_permissions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Teknisyen Yetkisi',
                'verbose_name_plural': 'Teknisyen Yetkileri',
            },
        ),
        migrations.CreateModel(
            name='TechnicianStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_statuses', to='tenants.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='technician',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='technicians.technicianstatus', verbose_name='Durum'),
        ),
    ]
