# Generated by Django 5.2.9 on 2026-06-22 09:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('services', '0001_initial'),
        ('technicians', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Mesai Başlangıç')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Mesai Bitiş')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Teknisyen')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_shifts', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Teknisyen Mesaisi',
                'verbose_name_plural': 'Teknisyen Mesaileri',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='LocationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('customer_latitude', models.FloatField(blank=True, null=True)),
                ('customer_longitude', models.FloatField(blank=True, null=True)),
                ('last_distance_meters', models.FloatField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_logs', to='customers.customer')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_logs', to='services.service')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_logs', to='technicians.technician')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Konum Takip Logu',
                'verbose_name_plural': 'Konum Takip Loglari',
                'ordering': ['-arrived_at'],
                'indexes': [models.Index(fields=['user', 'arrived_at'], name='technicians_user_id_8a687a_idx'), models.Index(fields=['service', 'arrived_at'], name='technicians_service_d20c00_idx'), models.Index(fields=['left_at'], name='technicians_left_at_c95465_idx')],
            },
        ),
        migrations.CreateModel(
            name='TechnicianAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('status', models.CharField(choices=[('worked', 'Calisti'), ('leave', 'Izinli'), ('sick', 'Raporlu'), ('offday', 'Resmi Tatil'), ('absent', 'Devamsiz')], default='worked', max_length=20, verbose_name='Durum')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Baslangic Saati')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Bitis Saati')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Not')),
                ('source', models.CharField(choices=[('manual', 'Manuel'), ('shift', 'Mesai')], default='manual', max_length=20, verbose_name='Kaynak')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncellenme Tarihi')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='technicians.technician', verbose_name='Teknisyen')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_attendances', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Teknisyen Devam Durumu',
                'verbose_name_plural': 'Teknisyen Devam Durumlari',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['technician', 'date'], name='technicians_technic_d864f8_idx'), models.Index(fields=['date'], name='technicians_date_a68bbe_idx')],
                'unique_together': {('technician', 'date')},
            },
        ),
    ]
