# Generated by Django 5.1.15 on 2026-09-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0002_technicianshift_locationlog_technicianattendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationlog',
            options={'ordering': ['-arrived_at'], 'verbose_name': 'Konum Takip Kaydı', 'verbose_name_plural': 'Konum Takip Kayıtları'},
        ),
        migrations.AlterModelOptions(
            name='technicianattendance',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Teknisyen Devam Durumu', 'verbose_name_plural': 'Teknisyen Devam Durumları'},
        ),
    ]
