# Generated by Django 5.1.15 on 2026-07-19 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveIntegerField(editable=False)),
                ('premium_started_at', models.DateField()),
                ('renewal_date', models.DateField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-period_number'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'period_number'), name='unique_tenant_membership_period')],
            },
        ),
    ]
