# Generated by Django 5.1.15 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='plan',
            field=models.CharField(choices=[('trial', 'Deneme'), ('premium', 'Premium')], default='premium', max_length=20),
        ),
    ]