# Generated by Django 5.2.9 on 2026-06-24 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('bug', 'Hata'), ('suggestion', 'Oneri'), ('complaint', 'Sikayet'), ('other', 'Diger')], default='other', max_length=20, verbose_name='Tur')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj/Aciklama')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('in_progress', 'Inceleniyor'), ('resolved', 'Cozuldu'), ('closed', 'Kapatildi')], default='new', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncellenme Tarihi')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='tenants.tenant', verbose_name='Tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Kullanici')),
            ],
            options={
                'verbose_name': 'Geri Bildirim',
                'verbose_name_plural': 'Geri Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
    ]
