# Generated by Django 5.2.9 on 2026-06-23 22:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technicians', '0002_technicianshift_locationlog_technicianattendance'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('total_premiums', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('approved', 'Onaylandi'), ('paid', 'Odendi'), ('cancelled', 'Iptal')], default='draft', max_length=20)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='technicians.technician')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='PayrollComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('addition', 'Eklenti'), ('deduction', 'Kesinti')], max_length=15)),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='hr.payroll')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_components', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('addition', 'Eklenti'), ('deduction', 'Kesinti')], max_length=15)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_templates', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianCompensation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salary_type', models.CharField(choices=[('net', 'Net'), ('gross', 'Brüt')], default='net', max_length=10)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('sgk_number', models.CharField(blank=True, max_length=50, null=True)),
                ('technician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compensation', to='technicians.technician')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_compensations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Teknisyen Özlük',
                'verbose_name_plural': 'Teknisyen Özlük Bilgileri',
            },
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.UniqueConstraint(fields=('technician', 'period_start', 'period_end'), name='unique_payroll_period'),
        ),
        migrations.AddConstraint(
            model_name='payrolltemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'name', 'type'), name='unique_payroll_template_per_tenant'),
        ),
    ]
