# Generated by Django 5.2.9 on 2026-06-22 11:09

import core.utils
import django.db.models.deletion
import django.utils.timezone
import services.models
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class ConvertServiceIdToUuid(Operation):
    """Convert the legacy Service bigint primary key without data loss."""

    reversible = False

    def state_forwards(self, app_label, state):
        state.alter_field(
            app_label,
            'service',
            'id',
            models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
            preserve_default=True,
        )

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            # LocationLog is created by technicians.0002 before this migration
            # and still references the legacy bigint Service primary key.
            schema_editor.execute(
                "ALTER TABLE technicians_locationlog "
                "DROP CONSTRAINT IF EXISTS technicians_location_service_id_1b468259_fk_services_; "
                "ALTER TABLE technicians_locationlog "
                "ALTER COLUMN service_id TYPE uuid "
                "USING CASE WHEN service_id IS NULL THEN NULL "
                "ELSE ('00000000-0000-0000-0000-' || "
                "lpad(to_hex(service_id), 12, '0'))::uuid END; "
                "ALTER TABLE services_service "
                "ALTER COLUMN id DROP IDENTITY IF EXISTS; "
                "ALTER TABLE services_service "
                "ALTER COLUMN id DROP DEFAULT; "
                "ALTER TABLE services_service "
                "ALTER COLUMN id TYPE uuid "
                "USING ('00000000-0000-0000-0000-' || "
                "lpad(to_hex(id), 12, '0'))::uuid; "
                "ALTER TABLE technicians_locationlog "
                "ADD CONSTRAINT technicians_location_service_id_1b468259_fk_services_ "
                "FOREIGN KEY (service_id) REFERENCES services_service (id) "
                "ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED"
            )
            return

        from_model = from_state.apps.get_model(app_label, 'Service')
        to_model = to_state.apps.get_model(app_label, 'Service')
        schema_editor.alter_field(
            from_model,
            from_model._meta.get_field('id'),
            to_model._meta.get_field('id'),
        )

    def describe(self):
        return 'Convert the Service primary key from bigint to UUID'


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        ('services', '0001_initial'),
        ('technicians', '0002_technicianshift_locationlog_technicianattendance'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'Servis', 'verbose_name_plural': 'Servisler'},
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='customers.customer', verbose_name='Müşteri'),
        ),
        migrations.AddField(
            model_name='service',
            name='customer_address',
            field=models.TextField(blank=True, null=True, verbose_name='Müşteri Adresi'),
        ),
        migrations.AddField(
            model_name='service',
            name='customer_full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Müşteri Adı Soyadı'),
        ),
        migrations.AddField(
            model_name='service',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Müşteri Telefonu'),
        ),
        migrations.AddField(
            model_name='service',
            name='fault_description',
            field=models.TextField(blank=True, null=True, verbose_name='Arıza Açıklaması'),
        ),
        migrations.AddField(
            model_name='service',
            name='receipt_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Fatura Numarası'),
        ),
        migrations.AddField(
            model_name='service',
            name='scheduled_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Randevu Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='technicians.technician', verbose_name='Teknisyen'),
        ),
        migrations.AddField(
            model_name='service',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_services', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        ConvertServiceIdToUuid(),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Marka Adı')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan Marka Mu?')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_brands', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markalar',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='device_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.brand', verbose_name='Cihaz MarkasÄ±'),
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.devicetype', verbose_name='Cihaz TÃ¼rÃ¼'),
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Model Adı')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan Model Mu?')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.brand', verbose_name='Marka')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_models', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Modeller',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='device_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.model', verbose_name='Cihaz Modeli'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Ödeme Yöntemi')),
                ('bank_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Banka Adı')),
                ('account_holder', models.CharField(blank=True, max_length=120, null=True, verbose_name='Hesap Sahibi')),
                ('iban', models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan Ödeme Yöntemi')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_payment_methods', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOperations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='İşlem Adı')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='İşlem/Parça Açıklaması')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Birim Fiyat')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_operations', to='products.product', verbose_name='Ürün/Malzeme')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.service', verbose_name='Servis')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_operations_list', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Servis İşlemi',
                'verbose_name_plural': 'Servis İşlemleri',
            },
        ),
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ödenen Tutar')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ödeme Tarihi')),
                ('payment_method', models.ForeignKey(default=services.models.get_default_payment_type, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.paymentmethod', verbose_name='Ödeme Yöntemi')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.service', verbose_name='Servis')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_payments', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Servis Ödemesi',
                'verbose_name_plural': 'Servis Ödemeleri',
            },
        ),
        migrations.CreateModel(
            name='ServicePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=core.utils.tenant_directory_path, verbose_name='Fotoğraf')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='services.service', verbose_name='Servis')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_photos', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Servis Fotoğrafı',
                'verbose_name_plural': 'Servis Fotoğrafları',
            },
        ),
        migrations.CreateModel(
            name='ServiceSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_signature', models.ImageField(blank=True, null=True, upload_to=core.utils.tenant_directory_path, verbose_name='Müşteri İmzası')),
                ('technician_signature', models.ImageField(blank=True, null=True, upload_to=core.utils.tenant_directory_path, verbose_name='Teknisyen İmzası')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='services.service', verbose_name='Servis')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_signatures', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Servis İmzası',
                'verbose_name_plural': 'Servis İmzaları',
            },
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30)),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(default='#6B7280', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('is_terminal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_statuses', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Servis Durumu',
                'verbose_name_plural': 'Servis Durumlari',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicestatus', verbose_name='Servis Durumu'),
        ),
        migrations.CreateModel(
            name='ServiceTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=20, verbose_name='Eski Durum')),
                ('new_status', models.CharField(max_length=20, verbose_name='Yeni Durum')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Tarihi')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='services.service', verbose_name='Servis')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_timelines', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Servis Zaman Çizelgesi',
                'verbose_name_plural': 'Servis Zaman Çizelgeleri',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_no', models.CharField(editable=False, max_length=24, unique=True, verbose_name='Belge No')),
                ('warranty_months', models.PositiveIntegerField(default=24, verbose_name='Garanti Süresi (Ay)')),
                ('coverage_details', models.TextField(blank=True, default='Garanti Şartları:\n• Bu belge, servis kapsamında yapılan işçilik ve/veya değiştirilen parçalar için geçerlidir.\n• Garanti süresi belge üzerindeki başlangıç ve bitiş tarihleri arasında geçerlidir.\n• Kullanıcı hatası, darbe, sıvı teması, yetkisiz müdahale ve yanlış kullanım durumları garanti kapsamı dışındadır.\n• Garanti sadece bu servis kaydında belirtilen işlem ve parçaları kapsar.\n• Garanti değerlendirmesi, teknik inceleme sonucuna göre yapılır.', help_text='Her satıra bir madde yazabilirsiniz.', null=True, verbose_name='Garanti Kapsamı (Madde Madde)')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('expired', 'Süresi Doldu'), ('void', 'Geçersiz')], default='active', max_length=20, verbose_name='Durum')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('covered_operations', models.ManyToManyField(to='services.serviceoperations', verbose_name='Kapsanan İşlemler')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_certificate', to='services.service', verbose_name='Servis')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warranty_certificates', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Garanti Belgesi',
                'verbose_name_plural': 'Garanti Belgeleri',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOperationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='İşlem Adı')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Açıklama')),
                ('default_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Varsayılan Ücret')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_operation_templates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_operation_templates', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Servis İşlem Şablonu',
                'verbose_name_plural': 'Servis İşlem Şablonları',
                'ordering': ['name', '-created_at'],
                'indexes': [models.Index(fields=['name'], name='services_se_name_169267_idx'), models.Index(fields=['is_active'], name='services_se_is_acti_2de6fc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='servicestatus',
            index=models.Index(fields=['tenant', 'code'], name='services_se_tenant__4252b4_idx'),
        ),
        migrations.AddIndex(
            model_name='servicestatus',
            index=models.Index(fields=['is_active'], name='services_se_is_acti_42075e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicestatus',
            unique_together={('tenant', 'code')},
        ),
    ]
