# Generated by Django 5.2.9 on 2026-07-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_update_new_status_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Marka', 'verbose_name_plural': 'Markalar'},
        ),
        migrations.AlterModelOptions(
            name='devicetype',
            options={'ordering': ['name'], 'verbose_name': 'Cihaz Türü', 'verbose_name_plural': 'Cihaz Türleri'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['name'], 'verbose_name': 'Model', 'verbose_name_plural': 'Modeller'},
        ),
        migrations.AddField(
            model_name='serviceoperations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AddField(
            model_name='serviceoperations',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi'),
        ),
    ]
