# Generated by Django 5.2.9 on 2026-07-13 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_brand_options_alter_devicetype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoperations',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='serviceoperations',
            name='updated_at',
        ),
    ]
