# Generated by Django 5.1.15 on 2026-09-12 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_serviceoperations_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicestatus',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Servis Durumu', 'verbose_name_plural': 'Servis Durumları'},
        ),
        migrations.AlterField(
            model_name='service',
            name='device_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.brand', verbose_name='Cihaz Markası'),
        ),
        migrations.AlterField(
            model_name='service',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.devicetype', verbose_name='Cihaz Türü'),
        ),
    ]
