# Generated by Django 5.1.15 on 2026-07-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountdeletionrequest'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0002_tenantmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_platform_admin', True)), fields=('is_platform_admin',), name='single_platform_admin_user'),
        ),
    ]
