# Generated by Django 5.1.15 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_platform_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]