from django.urls import path
from .views import (BrandListCreateView, ModelListCreateView, 
                    TechnicianServiceListCreateView, TechnicianServiceRetrieveUpdateDestroyView, 
                    AdminServiceListCreateView, AdminServiceRetrieveUpdateDestroyView, DeviceTypeListCreateView, PaymentMethodListCreateView,
                    ServiceOperationsListCreateView, ServiceOperationTemplateListCreateView, ServicePaymentListCreateView, ServicePaymentRefundView, ServicePhotoListCreateView, ServiceSignatureListCreateView,
                    PublicServiceListView, PublicServiceDetailView, PublicServiceFormPDFView,
                    ServiceFormPDFView, ServiceWarrantyPDFView, ServiceFormEmailView, ServiceWhatsAppStatusLinkView)    
urlpatterns = [
    path('device-types/', DeviceTypeListCreateView.as_view(), name='device-type-list-create'),
    path('brands/', BrandListCreateView.as_view(), name='brand-list-create'),
    path('models/', ModelListCreateView.as_view(), name='model-list-create'),
    path('payment-methods/', PaymentMethodListCreateView.as_view(), name='payment-method-list-create'),
    path('service-operations/', ServiceOperationsListCreateView.as_view(), name='service-operation-list-create'),
    path('service-operation-templates/', ServiceOperationTemplateListCreateView.as_view(), name='service-operation-template-list-create'),
    path('service-payments/', ServicePaymentListCreateView.as_view(), name='service-payment-list-create'),
    path('service-payments/refund/', ServicePaymentRefundView.as_view(), name='service-payment-refund'),
    path('service-photos/', ServicePhotoListCreateView.as_view(), name='service-photo-list-create'),
    path('service-signatures/', ServiceSignatureListCreateView.as_view(), name='service-signature-list-create'),
    path('technician-services/', TechnicianServiceListCreateView.as_view(), name='technician-service-list-create'),
    path('technician-services/<uuid:pk>/', TechnicianServiceRetrieveUpdateDestroyView.as_view(), name='technician-service-retrieve-update-destroy'),
    path('admin-services/', AdminServiceListCreateView.as_view(), name='admin-service-list-create'),
    path('admin-services/<uuid:pk>/', AdminServiceRetrieveUpdateDestroyView.as_view(), name='admin-service-retrieve-update-destroy'),
    path('admin-services/<uuid:pk>/form-pdf/', ServiceFormPDFView.as_view(), name='admin-service-form-pdf'),
    path('admin-services/<uuid:pk>/warranty-pdf/', ServiceWarrantyPDFView.as_view(), name='admin-service-warranty-pdf'),
    path('admin-services/<uuid:pk>/send-form-email/', ServiceFormEmailView.as_view(), name='admin-service-send-form-email'),
    path('admin-services/<uuid:pk>/whatsapp-status-link/', ServiceWhatsAppStatusLinkView.as_view(), name='admin-service-whatsapp-status-link'),
    path('public-services/', PublicServiceListView.as_view(), name='public-service-list'),
    path('public-services/<uuid:pk>/', PublicServiceDetailView.as_view(), name='public-service-detail'),
    path('public-services/<uuid:pk>/form-pdf/', PublicServiceFormPDFView.as_view(), name='public-service-form-pdf'),
]
