# Generated by Django 5.2.9 on 2026-06-18 06:50

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Servis Yönetimi', max_length=255)),
                ('panel_url', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.utils.tenant_directory_path)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('max_users', models.PositiveIntegerField(default=10)),
                ('force_update', models.BooleanField(default=False)),
                ('store_update_url_android', models.URLField(blank=True, null=True)),
                ('store_update_url_ios', models.URLField(blank=True, null=True)),
                ('store_android_version', models.CharField(blank=True, max_length=20, null=True)),
                ('store_ios_version', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_configs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Firma Ayarları',
                'verbose_name_plural': 'Firma Ayarları',
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='uniq_company_config_tenant')],
            },
        ),
    ]
