# Generated by Django 5.2.9 on 2026-07-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'İşlem', 'verbose_name_plural': 'İşlemler'},
        ),
        migrations.AlterModelOptions(
            name='transactioncategory',
            options={'verbose_name': 'İşlem Kategorisi', 'verbose_name_plural': 'İşlem Kategorileri'},
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Gelir'), ('expense', 'Gider')], max_length=10, verbose_name='İşlem Türü'),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Kategori Adı'),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='type',
            field=models.CharField(choices=[('income', 'Gelir'), ('expense', 'Gider')], max_length=10, verbose_name='İşlem Türü'),
        ),
    ]
